## O dataset

O dataset a ser utilizado é o *IBM HR Analytics Employee Attrition & Performance*, disponível no Kaggle. O dataset contém informações sobre funcionários de uma empresa fictícia, como idade, gênero, estado civil, nível de satisfação, entre outros. O objetivo é prever a probabilidade de um funcionário sair da empresa.

[Link do Kaggle](https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset/data)

Os termos *attrition* ("atrito") e *turnover* ("rotatividade") são frequentemente usados de forma intercambiável no contexto de recursos humanos e gestão de força de trabalho, mas eles se referem a conceitos ligeiramente diferentes em relação às mudanças no número e na composição dos empregados dentro de uma organização. Compreender a distinção entre esses dois é importante para analisar e relatar com precisão a dinâmica da força de trabalho.

### Atrito

Atrito refere-se à redução gradual de empregados por meio de circunstâncias naturais, como aposentadoria, demissão voluntária por motivos pessoais, ou a decisão de não substituir empregados que estão de saída. Atrito pode levar a uma diminuição no tamanho da força de trabalho, mas é caracterizado por sua natureza voluntária e muitas vezes incontrolável. Organizações podem permitir o atrito para reduzir o tamanho de sua força de trabalho sem recorrer a demissões, vendo isso como uma forma menos disruptiva de ajustar seus níveis de pessoal.

Em análises, quando você está analisando um conjunto de dados para atrito, você frequentemente olha para as razões por trás das saídas voluntárias e a taxa na qual estas ocorrem naturalmente ao longo do tempo. Taxas de atrito podem fornecer insights sobre a satisfação dos empregados e tendências de longo prazo da força de trabalho.

### Rotatividade

Rotatividade, por outro lado, engloba um escopo mais amplo de partidas de empregados, incluindo tanto renúncias voluntárias quanto demissões involuntárias (como demissões ou términos por justa causa). Porém, ocorre a substituição da força de trabalho. Rotatividade é uma medida de quantos empregados estão deixando a companhia por qualquer motivo. Uma alta taxa de rotatividade pode indicar problemas com satisfação no trabalho, cultura do local de trabalho, ou estabilidade organizacional, e frequentemente requer ação da gestão para endereçar as causas subjacentes.

Rotatividade é calculada dividindo o número de empregados que saem pelo número médio de empregados, geralmente em uma base anual, e expressando isso como uma porcentagem. Esta métrica é crucial para entender como as saídas de empregados, tanto voluntárias quanto involuntárias, afetam a capacidade da organização de manter uma força de trabalho estável e eficaz.

### Diferenças Chave

- **Natureza**: Atrito geralmente é voluntário e pode ser devido a fatores naturais ou incontroláveis, enquanto rotatividade inclui tanto saídas voluntárias quanto demissões involuntárias.
- **Implicações para Gestão**: Atrito pode ser parte de uma estratégia de ajuste natural da força de trabalho e nem sempre é negativo, enquanto alta rotatividade é frequentemente um sinal de problemas dentro da organização que precisam ser abordados.
- **Foco Estratégico**: Análise de atrito pode focar em entender tendências de longo prazo da força de trabalho e planejamento de aposentadoria, enquanto análise de rotatividade é frequentemente usada para identificar questões imediatas com satisfação de empregados, engajamento, ou práticas de gestão que podem estar impactando a retenção de staff.

Enquanto ambos atrito e rotatividade lidam com empregados deixando a organização, eles diferem em seu escopo e as implicações estratégicas para gerenciar e entender a dinâmica da força de trabalho. No seu conjunto de dados de empregados, distinguir entre atrito e rotatividade pode ajudar na customização de estratégias para planejamento da força de trabalho, retenção e desenvolvimento organizacional.

|    | Name                       | Description                                                                                                                                                    |
|---:|:---------------------------|:---------------------------------------------------------------------------------------------------------------------------------------------------------------|
|  0 | Age                        | Numerical Value                                                                                                                                                |
|  1 | Attrition                  | Employee leaving the company - Text - No, Yes                                                                                                                     |
|  2 | BusinessTravel            | Text - Non-Travel, Travel_Frequently, Travel_Rarely                                                                                                             |
|  3 | DailyRate                 | Numerical Value - Salary Level                                                                                                                                 |
|  4 | Department                 | Text - Sales, Research & Development, Human Resources                                                                                                         |
|  5 | DistanceFromHome         | Numerical Value - the distance from work to home in miles 
|  6 | Education                  | Numerical Value - 1=Below college, 2=College, 3=Bachelor, 4=Master, 5=PhD   |
|  7 | EducationField            | Text - Life Sciences, Medical, Marketing, Techincal Degree, Human Resources, Other                                                                                   |
|  8 | EmployeeCount             | Numerical Value - 1                                                                                                                                               |
|  9 | EmployeeNumber            | Numerical Value - Employee ID                                                                                                                                  |
| 10 | EnvironmentSatisfaction    | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High |
| 11 | Gender                     | Text - Female, Male                                                                                                                                             |
| 12 | HourlyRate                | Numerical Value - Hourly Salary                                                                                                                                |
| 13 | JobInvolvement            | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 14 | JobLevel                  | Numerical Value - 1, 2, 3, 4, 5. Means different job levels                                                                                                     |
| 15 | JobRole                   | Text - Sales Executive, Research Scientist, Laboratory Technician, Manufacturing Director, Healthcare Representative, Manager, Sales Representative, Research Director, Human Resources |
| 16 | JobSatisfaction           | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 17 | MaritalStatus             | Text - Single, Married, Divorced                                                                                                                                      |
| 18 | MonthlyIncome             | Numerical Value - Monthly Salary                                                                                                                               |
| 19 | MonthlyRate                | Numerical Value - Monthly Rate                                                                                                                                  |
| 20 | NumCompaniesWorked        | Numerical Value - Number of companies worked at                                                                                                                |
| 21 | Over18                    | Text - Y                                                                                                                                                    |
| 22 | Overtime                   | Text - No, Yes                                                                                                                                                    |
| 23 | PercentSalaryHike        | Numerical Value - Percentage increase in salary                                                                                                                |
| 24 | PerformanceRating         | Numerical Value - 1=Low, 2=Good, 3=Excellent, 4=Outstanding                                                                                                    |
| 25 | RelationshipSatisfaction  | Numerical Value - 1=Low, 2=Medium, 3=High, 4=Very High                                                                                                         |
| 26 | StandardHours             | Numerical Value - 80                                                                                                                                            |
| 27 | StockOptionsLevel        | Numerical Value - 0, 1, 2, 3                                                                                                                                    |
| 28 | TotalWorkingYears        | Numerical Value - Total years worked                                                                                                                            |
| 29 | TrainingTimesLastYear   | Numerical Value - How many times the employee has been trained last year                                                                                       |
| 30 | WorkLifeBalance          | Numerical Value - 1=Bad, 2=Good, 3=Better, 4=Best                                                                                                              |
| 31 | YearsAtCompany           | Numerical Value - Number of years at the company                                                                                                                |
| 32 | YearsInCurrentRole      | Numerical Value -Number of years in current role                                                                                                                |
| 33 | YearsSinceLastPromotion | Numerical Value - Years since last promotion                                                                                                                    |
| 34 | YearsWithCurrManager | Numerical Value - Years with current manager                                                                                                                    |

## Checagens básicas

- shape
- colunas
- tipos
- valores nulos
- valores "estranhos"
- valores únicos
- valores duplicados
- contagem de valores relevantes

In [1]:
import pandas as pd

DADOS = r".\Dados\employee_attrition.csv"

df = pd.read_csv(DADOS)

display(df)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [2]:
with pd.option_context("display.max_columns", 35):
    display(df.head())

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,2,Female,94,3,2,Sales Executive,4,Single,5993,19479,8,Y,Yes,11,3,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,3,Male,61,2,2,Research Scientist,2,Married,5130,24907,1,Y,No,23,4,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,4,Male,92,2,1,Laboratory Technician,3,Single,2090,2396,6,Y,Yes,15,3,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,4,Female,56,3,1,Research Scientist,3,Married,2909,23159,1,Y,Yes,11,3,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,1,Male,40,3,1,Laboratory Technician,2,Married,3468,16632,9,Y,No,12,3,4,80,1,6,3,3,2,2,2,2

In [3]:
df.shape

(1470, 35)

In [4]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [6]:
with pd.option_context("float_format", "{:.2f}".format):
    for column in df.columns:
        display(df[column].describe().to_frame())

          Age
count 1470.00
mean    36.92
std      9.14
min     18.00
25%     30.00
50%     36.00
75%     43.00
max     60.00

       Attrition
count       1470
unique         2
top           No
freq        1233

       BusinessTravel
count            1470
unique              3
top     Travel_Rarely
freq             1043

       DailyRate
count    1470.00
mean      802.49
std       403.51
min       102.00
25%       465.00
50%       802.00
75%      1157.00
max      1499.00

                    Department
count                     1470
unique                       3
top     Research & Development
freq                       961

       DistanceFromHome
count           1470.00
mean               9.19
std                8.11
min                1.00
25%                2.00
50%                7.00
75%               14.00
max               29.00

       Education
count    1470.00
mean        2.91
std         1.02
min         1.00
25%         2.00
50%         3.00
75%         4.00
max         5.00

       EducationField
count            1470
unique              6
top     Life Sciences
freq              606

       EmployeeCount
count        1470.00
mean            1.00
std             0.00
min             1.00
25%             1.00
50%             1.00
75%             1.00
max             1.00

       EmployeeNumber
count         1470.00
mean          1024.87
std            602.02
min              1.00
25%            491.25
50%           1020.50
75%           1555.75
max           2068.00

       EnvironmentSatisfaction
count                  1470.00
mean                      2.72
std                       1.09
min                       1.00
25%                       2.00
50%                       3.00
75%                       4.00
max                       4.00

       Gender
count    1470
unique      2
top      Male
freq      882

       HourlyRate
count     1470.00
mean        65.89
std         20.33
min         30.00
25%         48.00
50%         66.00
75%         83.75
max        100.00

       JobInvolvement
count         1470.00
mean             2.73
std              0.71
min              1.00
25%              2.00
50%              3.00
75%              3.00
max              4.00

       JobLevel
count   1470.00
mean       2.06
std        1.11
min        1.00
25%        1.00
50%        2.00
75%        3.00
max        5.00

                JobRole
count              1470
unique                9
top     Sales Executive
freq                326

       JobSatisfaction
count          1470.00
mean              2.73
std               1.10
min               1.00
25%               2.00
50%               3.00
75%               4.00
max               4.00

       MaritalStatus
count           1470
unique             3
top          Married
freq             673

       MonthlyIncome
count        1470.00
mean         6502.93
std          4707.96
min          1009.00
25%          2911.00
50%          4919.00
75%          8379.00
max         19999.00

       MonthlyRate
count      1470.00
mean      14313.10
std        7117.79
min        2094.00
25%        8047.00
50%       14235.50
75%       20461.50
max       26999.00

       NumCompaniesWorked
count             1470.00
mean                 2.69
std                  2.50
min                  0.00
25%                  1.00
50%                  2.00
75%                  4.00
max                  9.00

       Over18
count    1470
unique      1
top         Y
freq     1470

       OverTime
count      1470
unique        2
top          No
freq       1054

       PercentSalaryHike
count            1470.00
mean               15.21
std                 3.66
min                11.00
25%                12.00
50%                14.00
75%                18.00
max                25.00

       PerformanceRating
count            1470.00
mean                3.15
std                 0.36
min                 3.00
25%                 3.00
50%                 3.00
75%                 3.00
max                 4.00

       RelationshipSatisfaction
count                   1470.00
mean                       2.71
std                        1.08
min                        1.00
25%                        2.00
50%                        3.00
75%                        4.00
max                        4.00

       StandardHours
count        1470.00
mean           80.00
std             0.00
min            80.00
25%            80.00
50%            80.00
75%            80.00
max            80.00

       StockOptionLevel
count           1470.00
mean               0.79
std                0.85
min                0.00
25%                0.00
50%                1.00
75%                1.00
max                3.00

       TotalWorkingYears
count            1470.00
mean               11.28
std                 7.78
min                 0.00
25%                 6.00
50%                10.00
75%                15.00
max                40.00

       TrainingTimesLastYear
count                1470.00
mean                    2.80
std                     1.29
min                     0.00
25%                     2.00
50%                     3.00
75%                     3.00
max                     6.00

       WorkLifeBalance
count          1470.00
mean              2.76
std               0.71
min               1.00
25%               2.00
50%               3.00
75%               3.00
max               4.00

       YearsAtCompany
count         1470.00
mean             7.01
std              6.13
min              0.00
25%              3.00
50%              5.00
75%              9.00
max             40.00

       YearsInCurrentRole
count             1470.00
mean                 4.23
std                  3.62
min                  0.00
25%                  2.00
50%                  3.00
75%                  7.00
max                 18.00

       YearsSinceLastPromotion
count                  1470.00
mean                      2.19
std                       3.22
min                       0.00
25%                       0.00
50%                       1.00
75%                       3.00
max                      15.00

       YearsWithCurrManager
count               1470.00
mean                   4.12
std                    3.57
min                    0.00
25%                    2.00
50%                    3.00
75%                    7.00
max                   17.00

In [7]:
display(df.nunique())

remove_single_value_columns = [column for column, value in df.nunique().items() if value == 1]

print(f"{remove_single_value_columns = }")

Age                           43
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1470
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyIncome               1349
MonthlyRate                 1427
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

remove_single_value_columns = ['EmployeeCount', 'Over18', 'StandardHours']

In [8]:
df.duplicated().sum()

0

**Explicando quartis e outliers**

Quartis são valores que dividem um conjunto de dados em quatro partes iguais. O primeiro quartil (Q1) é o valor que deixa 25% dos dados abaixo e 75% acima. O segundo quartil (Q2) é a mediana, que deixa 50% dos dados abaixo e 50% acima. O terceiro quartil (Q3) deixa 75% dos dados abaixo e 25% acima. 

Por exemplo, se temos um conjunto de dados com 100 valores, o primeiro quartil (Q1) será o valor que deixa 25 valores abaixo e 75 acima. O segundo quartil (Q2) será o valor que deixa 50 valores abaixo e 50 acima. O terceiro quartil (Q3) será o valor que deixa 75 valores abaixo e 25 acima.

Outliers são valores que fogem do padrão do conjunto de dados. São valores muito altos ou muito baixos que podem influenciar negativamente na análise dos dados. Por exemplo, se temos um conjunto de dados com salários de funcionários de uma empresa, e um dos salários é muito maior que os outros, esse salário pode ser considerado um outlier.

Estatisticamente, um outlier é um valor que está a mais de 1,5 vezes o intervalo interquartil acima do terceiro quartil (Q3) ou a mais de 1,5 vezes o intervalo interquartil abaixo do primeiro quartil (Q1). O intervalo interquartil é a diferença entre o terceiro quartil (Q3) e o primeiro quartil (Q1).

In [9]:
with pd.option_context("float_format", "{:.2f}".format):
    display(df.describe())

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,...,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00,1470.00
mean,36.92,802.49,9.19,2.91,1.00,1024.87,2.72,65.89,2.73,2.06,...,2.71,80.00,0.79,11.28,2.80,2.76,7.01,4.23,2.19,4.12
std,9.14,403.51,8.11,1.02,0.00,602.02,1.09,20.33,0.71,1.11,...,1.08,0.00,0.85,7.78,1.29,0.71,6.13,3.62,3.22,3.57
min,18.00,102.00,1.00,1.00,1.00,1.00,1.00,30.00,1.00,1.00,...,1.00,80.00,0.00,0.00,0.00,1.00,0.00,0.00,0.00,0.00
25%,30.00,465.00,2.00,2.00,1.00,491.25,2.00,48.00,2.00,1.00,...,2.00,80.00,0.00,6.00,2.00,2.00,3.00,2.00,0.00,2.00
50%,36.00,802.00,7.00,3.00,1.00,1020.50,3.00,66.00,3.00,2.00,...,3.00,80.00,1.00,10.00,3.00,3.00,5.00,3.00,1.00,3.00
75%,43.00,1157.00,14.00,4.00,1.00,1555.75,4.00,83.75,3.00,3.00,...,4.00,80.00,1.00,15.00,3.00,3.00,9.00,7.00,3.00,7.00
max,60.00,1499.00,29.00,5.00,1.00,2068.00,4.00,100.00,4.00,5.00,...,4.00,80.00,3.00,40.00,6.00,4.00,40.00,18.00,15.00,17.00

In [10]:
# Usando a coluna Age
# intervalo_interquartil = 1.5 * (Age.quantile(75%) - Age.quantile(25%))
intervalo_interquartil = 1.5 * (1157 - 465)

# Outlier = (Age.quantile(25%) - intervalo_interquartil) | (Age.quantile(75%) + intervalo_interquartil)

outlier_abaixo = 465 - intervalo_interquartil
outlier_acima = 1157 + intervalo_interquartil

print(f"{intervalo_interquartil = }")
print(f"{outlier_abaixo = }")
print(f"{outlier_acima = }")

intervalo_interquartil = 1038.0
outlier_abaixo = -573.0
outlier_acima = 2195.0

In [11]:
for column in df.select_dtypes("number").columns:
    if column in remove_single_value_columns:
        continue

    intervalo_interquartil = 1.5 * (df[column].quantile(0.75) - df[column].quantile(0.25))
    outlier_abaixo = df[column].quantile(0.25) - intervalo_interquartil
    outlier_acima = df[column].quantile(0.75) + intervalo_interquartil

    df_coluna_analisada = df[column][(df[column] < outlier_abaixo) | (df[column] > outlier_acima)]

    if df_coluna_analisada.count() > 0:
        display(df_coluna_analisada.to_frame())
        print(f"Rows: {df_coluna_analisada.count()}")

      MonthlyIncome
25            19094
29            18947
45            19545
62            18740
105           18844
...             ...
1374          17875
1377          19161
1401          19636
1437          19431
1443          18880

[114 rows x 1 columns]

Rows: 114

      NumCompaniesWorked
4                      9
38                     9
50                     9
95                     9
105                    9
122                    9
194                    9
198                    9
208                    9
245                    9
287                    9
290                    9
334                    9
371                    9
372                    9
385                    9
393                    9
401                    9
440                    9
447                    9
456                    9
525                    9
541                    9
544                    9
551                    9
575                    9
597                    9
617                    9
623                    9
660                    9
714                    9
717                    9
756                    9
770                    9
779                    9
789                    9
816                    9
837                    9
927                    9
947                    9
957                    9
1000                   9
1035                   9
1117                   9
1145                   9
1162                   9
1172                   9
1219                   9
1262                   9
1296                   9
1357                   9
1442                   9

Rows: 52

      PerformanceRating
1                     4
6                     4
7                     4
8                     4
21                    4
...                 ...
1441                  4
1445                  4
1446                  4
1447                  4
1467                  4

[226 rows x 1 columns]

Rows: 226

      StockOptionLevel
6                    3
64                   3
65                   3
83                   3
88                   3
...                ...
1402                 3
1415                 3
1440                 3
1442                 3
1457                 3

[85 rows x 1 columns]

Rows: 85

      TotalWorkingYears
18                   31
62                   29
85                   37
98                   38
105                  30
...                 ...
1264                 34
1301                 37
1331                 29
1374                 29
1401                 35

[63 rows x 1 columns]

Rows: 63

      TrainingTimesLastYear
0                         0
10                        5
16                        5
20                        5
23                        6
...                     ...
1436                      6
1448                      5
1458                      5
1466                      5
1467                      0

[238 rows x 1 columns]

Rows: 238

      YearsAtCompany
18                25
28                22
45                22
62                27
63                21
...              ...
1403              20
1404              20
1443              22
1445              20
1462              20

[104 rows x 1 columns]

Rows: 104

      YearsInCurrentRole
45                    15
63                    16
123                   18
187                   15
190                   18
231                   17
281                   16
417                   15
466                   16
595                   15
716                   16
746                   16
861                   15
976                   16
1024                  17
1150                  15
1156                  15
1221                  15
1327                  17
1351                  17
1430                  16

Rows: 21

      YearsSinceLastPromotion
15                          8
45                         15
46                          8
55                          8
61                          9
...                       ...
1414                       12
1425                        8
1444                        9
1447                       11
1462                        9

[107 rows x 1 columns]

Rows: 107

      YearsWithCurrManager
28                      17
123                     15
153                     15
187                     15
231                     15
386                     17
561                     16
616                     17
635                     15
686                     17
875                     17
926                     17
1078                    17
1348                    16

Rows: 14

In [12]:
df.describe(exclude="number")

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

OBS.: *O dataset é desbalanceado, ou seja, a quantidade de funcionários que saíram da empresa é muito menor que a quantidade de funcionários que permaneceram na empresa. Isso pode influenciar na análise dos dados.*

A coluna "Attrition" é a coluna que indica se o funcionário saiu da empresa ou não. Ela é a chama coluna alvo, ou target. Esse nome é dado pois é a coluna que queremos avaliar e prever.

In [13]:
df_attrition = df[df["Attrition"] == "Yes"].drop(columns=remove_single_value_columns + ["Attrition"])
display(df_attrition)

,Age,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,2,Female,...,3,1,0,8,0,1,6,4,0,5
2,37,Travel_Rarely,1373,Research & Development,2,2,Other,4,4,Male,...,3,2,0,7,3,3,0,0,0,0
14,28,Travel_Rarely,103,Research & Development,24,3,Life Sciences,19,3,Male,...,3,2,0,6,4,3,4,2,0,3
21,36,Travel_Rarely,1218,Sales,9,4,Life Sciences,27,3,Male,...,4,2,0,10,4,3,5,3,0,3
24,34,Travel_Rarely,699,Research & Development,6,1,Medical,31,2,Male,...,3,3,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Travel_Frequently,638,Sales,9,3,Marketing,2023,4,Male,...,3,1,1,1,3,2,1,0,1,0
1442,29,Travel_Rarely,1092,Research & Development,1,4,Medical,2027,1,Male,...,3,2,3,4,3,4,2,2,2,2
1444,56,Travel_Rarely,310,Research & Development,7,2,Technical Degree,2032,4,Male,...,3,4,1,14,4,1,10,9,9,8
1452,50,Travel_Frequently,878,Sales,1,4,Life Sciences,2044,2,Male,...,3,4,2,12,3,3,6,3,0,1
1461,50,Travel_Rarely,410,Sales,28,3,Marketing,2055,4,Male,...,3,2,1,20,3,3,3,2,2,0